language: java
jdk:
  - oraclejdk8
install: mvn clean install -DskipTests=true
deploy:
  provider: releases
  user: "35051921@qq.com"
  password: "how****812***"
  skip_cleanup: true
  on:
    tags: true
